
@baseUrl = https://game-view-api.onrender.com
### Jogador - get all

### Jogador - get all
GET {{baseUrl}}/jogador/all

### Classe - get all
GET {{baseUrl}}/classe/all

### Personagem - get all
GET {{baseUrl}}/personagem/all

### Guilda - get all
GET {{baseUrl}}/guilda/all

### Missao - get all
GET {{baseUrl}}/missao/all

### Monstro - get all
GET {{baseUrl}}/monstro/all

### Missao Registro - get all
GET {{baseUrl}}/missaoregistro/all

### Batalha Registro - get all
GET {{baseUrl}}/batalharegistro/all

### Aliado - get all
GET {{baseUrl}}/aliado/all
